---
name: Verify and Bump
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ github.token }}
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.5
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "example/examplea"
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.5
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "example/examplea"
      - name: Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "example/examplea"
          framework: terraform
          soft-fail: "false"
          output: "cli"
          api-key-variable: ${{ secrets.BC_API_KEY }}
