---
name: pull_request
on: pull_request
env:
  terraform: 0.14.5
  tf_target_dir: example/examplea
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform }}
          tf_actions_subcommand: init
          tf_actions_working_dir: ${{ env.tf_target_dir }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform }}
          tf_actions_subcommand: validate
          tf_actions_working_dir: ${{ env.tf_target_dir }}

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - name: Run Bridgecrew scanner
        id: BridgecrewScanner
        uses: bridgecrewio/bridgecrew-action@master
        with:
          directory: ${{ env.tf_target_dir }}
          soft-fail: "false"
          output: "cli"
          api-key-variable: ${{ secrets.BC_API_KEY }}
