---
name: pr-test
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Bridgecrew scanner
        id: BridgecrewScanner
        uses: bridgecrewio/bridgecrew-action@master
        with:
          directory: "example/examplea"
          soft-fail: "false"
          output: "cli"
          api-key-variable: ${{ secrets.BC_API_KEY }}
  validate-tf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.5
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "example/examplea"
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.5
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "example/examplea"
